steps:
  - name: 'hashicorp/terraform:1.9'
    id: terraform-init
    entrypoint: 'terraform'
    args: ['init']
  - name: 'hashicorp/terraform:1.9'
    id: terraform-plan
    entrypoint: 'terraform'
    args: ['plan', '-out=tfplan']
  - name: 'hashicorp/terraform:1.9'
    id: terraform-apply
    entrypoint: 'terraform'
    args: ['apply', 'tfplan']

# ADD THIS SECTION:
options:
  logging: CLOUD_LOGGING_ONLY  # ✅ Fixes your error!
