steps:
  # Install & init Terraform
  - name: 'hashicorp/terraform:1.9'
    id: terraform-init
    entrypoint: 'terraform'
    args: ['init']
  
  # Plan (shows what will be created)
  - name: 'hashicorp/terraform:1.9'
    id: terraform-plan
    entrypoint: 'terraform'
    args: ['plan']
  
  # CREATE BUCKET!
  - name: 'hashicorp/terraform:1.9'
    id: terraform-apply
    entrypoint: 'terraform'
    args: ['apply', '-auto-approve']

options:
  logging: CLOUD_LOGGING_ONLY
